spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: youremail@example.com
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true